### PR TITLE
Update Fred2 from version 2.0.6 to 2.0.7

### PR DESCRIPTION
**Pull request by skrakau**
Update Fred2.

Maybe we can improve the changelog in another PR.

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/epitopeprediction branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/epitopeprediction)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by skrakau** [comment]
The CI failed because 1) https://github.com/nf-core/epitopeprediction/pull/39 should have waited until Fred2 was updated to 2.0.7 (thought we updated this already) and 2) just realised that I only added the mouse alleles to methods in `ANN.py`, but not to syfpeithi in `PSSM.py`. Thus this should be updated in Fred2, and for this pipeline for now the `test_peptides_h2` should be run using `MHCNuggets` (or `MHCFlurry`)

**Review by christopher-mohr — CHANGES_REQUESTED** [review]
Thanks @skrakau! Currently there are not mouse PSSMs for Syfpeithi in FRED2, therefore we should make sure that only mhcflurry and mhcnuggets is used with mouse alleles (can be done in a separate PR). Could you just change the test accordingly in this PR please? I will take care about the changelog with the template merge.

**Comment by skrakau** [comment]
Ah forgot, makes sense then.

**Review by christopher-mohr — APPROVED** [review]

**Comment by christopher-mohr** [comment]
The test will be adapted in a separate PR.

**Pull request merged**
