### PR TITLE
Increase memory for mergeResults and mergeReports

### PR DESCRIPTION
**Pull request by skrakau**
I have relatively big result files that cause memory problems with the processes "mergeResults" and "mergeReports". I am not sure what other applications require, but maybe increasing memory for those processes a bit doesn't harm?

# 

Many thanks for contributing to nf-core/epitopeprediction!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/epitopeprediction branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/epitopeprediction)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by skrakau** [comment]
we agreed that we should add a parameter to differentiate the use cases...

**Comment by skrakau** [comment]
I am not sure how to do this best. Since the memory requirements can be anything between a few GB and hundreds of GB, I introduced 3 memory modes (to avoid at the same time that the user has to think too much about it). If it's not enough, the maxRetries would still apply. Maybe together with a proper documentation this could work? 

Any suggestions are welcome.

**Comment by christopher-mohr** [comment]
> I am not sure how to do this best. Since the memory requirements can be anything between a few GB and hundreds of GB, I introduced 3 memory modes (to avoid at the same time that the user has to think too much about it). If it's not enough memory, the maxRetries would still apply. Maybe together with a proper documentation this could work?
> 
> Any suggestions are welcome.

Maybe it would be helpful for the user if we give names to the mem modes such as `low`, intermediate` and `high`?

**Comment by ggabernet** [comment]
changelog was updated

**Pull request merged**
