### PR TITLE
Merge template 2.13.

### PR DESCRIPTION
**Pull request by jonasscheid**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/epitopeprediction _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jonasscheid** [comment]
@christopher-mohr thoughts on [this](https://github.com/nf-core/epitopeprediction/actions/runs/8005640460/job/21866073905?pr=234)? Running the tests locally worked fine

**Comment by christopher-mohr** [comment]
Can't reproduce on gitpod using `dev`

**Comment by christopher-mohr** [comment]
Fix is on `dev`, if you merge that, it should work. :)

**Comment by jonasscheid** [comment]
Great thanks! Always a minor thing with biomart🤦🏼. Can we push the release through today?

**Review by christopher-mohr — APPROVED** [review]
LGTM

**Pull request merged**
