### PR TITLE
Allele data can also be used via internet link in sample sheet

### PR DESCRIPTION
**Pull request by alina-bauer**
Now allele data as an internet link can also be used in pipeline. 
Restoring the functionality of the previous PR.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/epitopeprediction/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, also make a PR on the nf-core/epitopeprediction _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by jonasscheid — APPROVED** [review]
Local runs run through except grch38 -> #208

**Comment by christopher-mohr** [comment]
Just two comments:
- the pipeline does not accept `.alleles` files anymore now. Might not be necessary, just important to note that the behavior of the pipeline is changed.
- why do you want to handle "remotely stored" files manually in the python script? The file staging is done by the pipeline/nextflow functionality anyway.

**Comment by alina-bauer** [comment]
I will write it in my backlog.. the `.alleles` file will follow soon.
Yes I didn't have that in mind.. the file staging by nextflow is much easier, this functionality will follow soon together with the yet not used allele check.

**Comment by christopher-mohr** [comment]
> I will write it in my backlog.. the `.alleles` file will follow soon. Yes I didn't have that in mind.. the file staging by nextflow is much easier, this functionality will follow soon together with the yet not used allele check.

Thanks for the feedback!

**Pull request merged**
